name: Buzz Chat
description: Best social networking app
full_description: 'Buzz Chat is the newest social networking platform<br>
<br>With the best features ever:
<br>- AI Content moderation
<br>- Chatbots Integration
<br>- AI Content Generator'
android: https://expo.dev/artifacts/eas/pjMcnYsQQaYubfD8BauTXu.apk
iOS: https://expo.dev/artifacts/eas/pjMcnYsQQaYubfD8BauTXu.apk
web: https://buzzchat.site
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:

